# Generated by Django 4.2.28 on 2026-02-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('Amrita', 'amrita'), ('Others', 'others')], default='others', max_length=20)),
                ('user_role', models.CharField(choices=[('Registration', 'resgistration'), ('Finance', 'finance'), ('Participant', 'participant')], default='participant', max_length=20)),
            ],
        ),
    ]
