# Generated by Django 4.2.28 on 2026-02-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('registration', 'Registration'), ('finance', 'Finance'), ('admin', 'Admin'), ('participant', 'Participant')], default='participant', max_length=20),
        ),
    ]
