# Generated by Django 4.2.28 on 2026-02-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_seats',
            field=models.IntegerField(default=100),
        ),
    ]
