# Generated by Django 4.2.28 on 2026-02-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_rate',
            field=models.IntegerField(default=0),
        ),
    ]
