# Generated by Django 4.2.28 on 2026-02-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_total_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='total_seats',
        ),
    ]
